### ISSUE TITLE
Download links for the missing large files

### ISSUE THREAD

**Issue by JMing-Li** [niehu-szbl/scIBD_website_code#2]
Thanks for providing such a useful tool 👍 ！But the online page seems to be occasionally inaccessible, and I want to reproduce it locally. Since the `.h5ad` file in `./www/scanpy/` directory and those `.loom` files in `./www/scenic/` directory are too large to include in this Git repo, where can I download them?

**Comment by niehu-szbl** [comment]
Please check the code and data here
https://figshare.com/articles/software/scIBD_website_code/22731374
https://figshare.com/articles/dataset/Integrated_scRNA-seq_data_in_scIBD/22316641

**Comment by JMing-Li** [comment]
Thank you so much！
